###
POST http://localhost:9000/api/empresa HTTP/1.1
Content-Type: application/json

{
    "nombre": "Mall Aventura Piura",
    "email": "mallaqp@example.com",
    "telefono": 444555
}

###
GET http://localhost:9000/api/empresa HTTP/1.1
###
GET http://localhost:9000/api/empresa/65497f873f8790c59137811d HTTP/1.1

###
PUT http://localhost:9000/api/empresa/65497f873f8790c59137811d HTTP/1.1
Content-Type: application/json

{
    "nombre": "UNSAC",
    "email": "mallaqp@example.com",
    "telefono": 444555
}

###
DELETE http://localhost:9000/api/empresa/65498052f24512087c6228c1 HTTP/1.1



###
POST http://localhost:9000/api/nivel HTTP/1.1
Content-Type: application/json

{
    "nivel": "Arriba",
    
    "empresa": "65497f873f8790c59137811d"
}

###
GET http://localhost:9000/api/nivel HTTP/1.1
###
GET http://localhost:9000/api/nivel/654c2a581e5a7f6a278d117c HTTP/1.1
###

PUT http://localhost:9000/api/nivel/654d41c113614ad2250db535 HTTP/1.1
Content-Type: application/json

{
  "nivel": "Superior",
  "empresa": "65497f873f8790c59137811d"
}
###
DELETE http://localhost:9000/api/nivel/654c2a581e5a7f6a278d117c HTTP/1.1

###
POST http://localhost:9000/api/parking HTTP/1.1
Content-Type: application/json

{
    "nombre": "Mall Aventura Piura",
    "email": "mallaqp@example.com",
    "telefono": 444555
}
